const defaults={3:[C(-1.35,-.45),C(.05,1.25),C(1.25,-.55)],4:[C(-1.45,-.55),C(-.55,1.15),C(.72,.92),C(1.35,-.72)],5:[C(-1.55,-.58),C(-.72,1.12),C(.38,1.30),C(1.52,.15),C(.36,-1.30)],6:[C(-1.62,-.44),C(-1.08,.91),C(-.18,1.42),C(.92,1.05),C(1.55,-.18),C(.23,-1.38)],7:[C(-1.65,-.25),C(-1.25,.85),C(-.44,1.45),C(.48,1.34),C(1.33,.72),C(1.57,-.51),C(.08,-1.48)],8:[C(-1.7,-.2),C(-1.35,.82),C(-.65,1.42),C(.24,1.53),C(1.08,1.02),C(1.62,.25),C(1.22,-1.02),C(-.18,-1.48)]};
const state={n:5,Z:[],W:[],P:[],dP:[],F:[],c:C(0,0),zView:{cx:0,cy:0,half:2.5},dragging:null,renderQueued:false,fullRender:true};

function setFromRoots(roots){ const oldW=state.W; state.Z=roots.map(cloneC); state.n=state.Z.length; state.P=polyFromRoots(state.Z); state.dP=polyDerivative(state.P); state.W=matchPoints(oldW,solvePolynomial(state.dP,oldW)); state.F=polyIntegralZero(state.dP); state.c=polyEval(state.F,state.Z[0]); }
function setFromW(keepC=true){ const oldZ=state.Z.map(cloneC); state.dP=polyScale(polyFromRoots(state.W),state.n); state.F=polyIntegralZero(state.dP); if(!keepC) state.c=C(0,0); state.P=state.F.map(cloneC); state.P[0]=sub(state.P[0],state.c); state.Z=matchPoints(oldZ,solvePolynomial(state.P,oldZ)); }
function setC(c,{forcedRootIndex=null,forcedRootPoint=null}={}){ const oldZ=state.Z.map(cloneC); state.c=cloneC(c); state.P=state.F.map(cloneC); state.P[0]=sub(state.P[0],state.c); state.Z=matchPoints(oldZ,solvePolynomial(state.P,oldZ)); if(forcedRootIndex!==null && forcedRootPoint){ let nearest=0; for(let k=1;k<state.Z.length;k++) if(dist(state.Z[k],forcedRootPoint)<dist(state.Z[nearest],forcedRootPoint)) nearest=k; if(nearest!==forcedRootIndex) [state.Z[nearest],state.Z[forcedRootIndex]]=[state.Z[forcedRootIndex],state.Z[nearest]]; state.Z[forcedRootIndex]=cloneC(forcedRootPoint); } }
function reset(n=state.n){ state.n=n; setFromRoots((defaults[n]||defaults[5]).map(cloneC)); fitView(); }
function randomize(){ const roots=[]; for(let k=0;k<state.n;k++){ const t=2*Math.PI*k/state.n+(Math.random()-.5)*.45; const r=.75+Math.random()*.9; roots.push(C(r*Math.cos(t)+(Math.random()-.5)*.25,r*Math.sin(t)+(Math.random()-.5)*.25)); } setFromRoots(roots); fitView(); }

const plot=document.getElementById('plot'), svg=document.getElementById('svg'), bgCanvas=document.getElementById('bgCanvas'), NS='http://www.w3.org/2000/svg';
function dims(el){return{w:el.clientWidth,h:el.clientHeight}};
function toScreen(z){ const {w,h}=dims(plot), s=Math.min(w,h)/(2*state.zView.half); return {x:w/2+(z.re-state.zView.cx)*s,y:h/2-(z.im-state.zView.cy)*s}; }
function fromScreen(x,y){ const {w,h}=dims(plot), s=Math.min(w,h)/(2*state.zView.half); return C(state.zView.cx+(x-w/2)/s,state.zView.cy-(y-h/2)/s); }
function evtPoint(e,el){ const r=el.getBoundingClientRect(); return {x:e.clientX-r.left,y:e.clientY-r.top}; }
function svgEl(name,attrs={}){ const el=document.createElementNS(NS,name); for(const [k,v] of Object.entries(attrs)) el.setAttribute(k,v); return el; }
function clearSvg(node){ while(node.firstChild) node.removeChild(node.firstChild); }
function fitView(){ const disk=smallestEnclosingCircle(state.Z); const pts=state.Z.concat(state.W).concat([C(disk.center.re+disk.radius,disk.center.im),C(disk.center.re-disk.radius,disk.center.im),C(disk.center.re,disk.center.im+disk.radius),C(disk.center.re,disk.center.im-disk.radius)]); let minx=Infinity,maxx=-Infinity,miny=Infinity,maxy=-Infinity; for(const z of pts){minx=Math.min(minx,z.re);maxx=Math.max(maxx,z.re);miny=Math.min(miny,z.im);maxy=Math.max(maxy,z.im);} state.zView.cx=(minx+maxx)/2; state.zView.cy=(miny+maxy)/2; state.zView.half=Math.max(1,(maxx-minx)/2,(maxy-miny)/2)*1.32; scheduleRender(true); }
function resizeCanvas(){ const {w,h}=dims(plot); if(bgCanvas.width!==w||bgCanvas.height!==h){ bgCanvas.width=w; bgCanvas.height=h; } svg.setAttribute('viewBox',`0 0 ${w} ${h}`); return {w,h}; }
function drawGrid(){ const {w,h}=dims(plot), s=Math.min(w,h)/(2*state.zView.half); const step=niceStep(state.zView.half*2/8); const x0=state.zView.cx-state.zView.half, x1=state.zView.cx+state.zView.half, y0=state.zView.cy-state.zView.half, y1=state.zView.cy+state.zView.half; for(let x=Math.ceil(x0/step)*step;x<=x1+1e-9;x+=step){ const p=toScreen(C(x,0)); svg.appendChild(svgEl('line',{x1:p.x,y1:0,x2:p.x,y2:h,class:Math.abs(x)<step*.2?'axis-line':'grid-line'})); } for(let y=Math.ceil(y0/step)*step;y<=y1+1e-9;y+=step){ const p=toScreen(C(0,y)); svg.appendChild(svgEl('line',{x1:0,y1:p.y,x2:w,y2:p.y,class:Math.abs(y)<step*.2?'axis-line':'grid-line'})); } }
function niceStep(raw){ const p=10**Math.floor(Math.log10(raw||1)); const m=raw/p; return (m<1.6?1:m<3.5?2:m<7.5?5:10)*p; }
function pointRadiusWorld(px=16){ const {w,h}=dims(plot); return px*(2*state.zView.half/Math.min(w,h)); }
function clusterTolerance(){ return Math.max(1e-8,state.zView.half*2e-6); }
function exactCluster(points,index){ const eps=clusterTolerance(); return points.map((p,i)=>dist(p,points[index])<=eps?i:-1).filter(i=>i>=0); }
function snapThreshold(){ return pointRadiusWorld(18); }
function allClusters(points){ const used=new Set(), groups=[]; for(let i=0;i<points.length;i++){ if(used.has(i)) continue; const g=exactCluster(points,i); g.forEach(j=>used.add(j)); groups.push(g); } return groups; }
function nearestSnapCluster(points,movedIds,target){ const moved=new Set(movedIds); let best=-1,bestD=snapThreshold(); for(let j=0;j<points.length;j++){ if(moved.has(j)) continue; const d=dist(target,points[j]); if(d<bestD){bestD=d;best=j;} } if(best<0) return null; const eps=clusterTolerance(); return points.map((p,i)=>(!moved.has(i)&&dist(p,points[best])<=eps)?i:-1).filter(i=>i>=0); }
function unsnapCluster(kind,index){ const pts=kind==='z'?state.Z:state.W; const ids=exactCluster(pts,index); if(ids.length<=1) return false; const center=cloneC(pts[index]), r=pointRadiusWorld(Math.max(10,5+2*ids.length)); ids.forEach((j,t)=>{ const ang=2*Math.PI*t/ids.length-Math.PI/2; pts[j]=add(center,scale(expi(ang),r)); }); if(kind==='z') setFromRoots(state.Z); else setFromW(true); return true; }

function hullData(){ const hull=convexHull(state.Z); return {hull, feather:Math.max(.03,state.zView.half*.10)}; }
function applyHullDimming(rgb,z){ const {hull,feather}=hullData(); if(hull.length<3) return rgb; const signed=signedDistanceToHull(z,hull); const outside=smoothstep(0,feather,-signed); if(outside<=0) return rgb; const lum=Math.round(.2126*rgb[0]+.7152*rgb[1]+.0722*rgb[2]); let muted=mixRgb(rgb,[lum,lum,lum],.75*outside); muted=mixRgb(muted,[9,17,23],.63*outside); return muted; }
function domainColor(z,value){ const m=Math.max(1e-300,abs(value)); const phase=(arg(value)+Math.PI)/(2*Math.PI); const log2m=Math.log2(m); const global=.54+.16*Math.tanh(log2m/4.6); const modulusMajor=periodicLine(log2m,.052); const modulusMinor=periodicLine(log2m-.5,.076); const phaseRay=periodicLine(phase*12,.042); let v=global+.19*modulusMajor+.05*modulusMinor-.08*phaseRay; v=Math.max(.12,Math.min(.97,v)); const sat=Math.max(.54,Math.min(.90,.82-.13*modulusMajor)); return applyHullDimming(hsvToRgb(phase,sat,v),z); }
