function drawBackground(highQuality=true){ const show=document.getElementById('bgToggle').checked; const {w,h}=resizeCanvas(); const ctx=bgCanvas.getContext('2d'); ctx.clearRect(0,0,w,h); if(!show) return; const side=Math.min(w,h); const N=highQuality?Math.max(190,Math.min(360,Math.round(side/2.25))):Math.max(84,Math.min(150,Math.round(side/5))); const off=document.createElement('canvas'); off.width=N; off.height=N; const octx=off.getContext('2d',{alpha:false}); const img=octx.createImageData(N,N); for(let j=0;j<N;j++) for(let i=0;i<N;i++){ const z=fromScreen((i+.5)/N*w,(j+.5)/N*h); const [r,g,b]=domainColor(z,polyEval(state.P,z)); const k=4*(j*N+i); img.data[k]=r; img.data[k+1]=g; img.data[k+2]=b; img.data[k+3]=255; } octx.putImageData(img,0,0); ctx.imageSmoothingEnabled=true; ctx.drawImage(off,0,0,w,h); }
function factorial(n){let f=1;for(let k=2;k<=n;k++)f*=k;return f;}
function localCriticalData(w,multiplicity){ const order=multiplicity+1, pw=polyEval(state.P,w); if(abs(pw)<1e-8) return null; let deriv=state.P; for(let k=0;k<order;k++) deriv=polyDerivative(deriv); const a=scale(polyEval(deriv,w),1/factorial(order)); if(abs(a)<1e-12) return null; return {order,pw,a,phase:arg(mul(pw,conj(a)))}; }
function flowBranches(w,multiplicity,up=false){ const local=localCriticalData(w,multiplicity); if(!local) return []; const {order,phase}=local; const eps=pointRadiusWorld(3.2), step=pointRadiusWorld(state.dragging?5.8:4.6); const maxSteps=state.dragging?360:760, paths=[]; const offset=up?0:Math.PI; for(let branch=0;branch<order;branch++){ const theta=(phase+offset+2*Math.PI*branch)/order; let z=add(w,scale(expi(theta),eps)); const pts=[cloneC(w),cloneC(z)]; for(let k=0;k<maxSteps;k++){ const p=polyEval(state.P,z), dp=polyEval(state.dP,z); let v=up?mul(p,conj(dp)):neg(mul(p,conj(dp))); let vm=abs(v); if(vm<1e-15||!finiteC(v)) break; v=scale(v,1/vm); const mid=add(z,scale(v,step*.5)); const pm=polyEval(state.P,mid), dpm=polyEval(state.dP,mid); let v2=up?mul(pm,conj(dpm)):neg(mul(pm,conj(dpm))); const v2m=abs(v2); if(v2m<1e-15||!finiteC(v2)) break; v2=scale(v2,1/v2m); z=add(z,scale(v2,step)); if(k%2===0) pts.push(cloneC(z)); if(!up && state.Z.some(r=>dist(z,r)<step*1.6)){pts.push(cloneC(z));break;} if(Math.abs(z.re-state.zView.cx)>state.zView.half*1.45||Math.abs(z.im-state.zView.cy)>state.zView.half*1.45) break; } paths.push(pts); } return paths; }
function compactWidgetGeometry(){ const {w,h}=dims(plot); const r=Math.min(w,h)*0.14, pad=14; return {cx:w-r-pad, cy:r+pad, radius:r, inner:r-10}; }
function criticalValues(){ return state.W.map(w=>polyEval(state.F,w)); }
function compactValueScale(values=criticalValues()){ const mags=values.map(abs).filter(m=>Number.isFinite(m)&&m>1e-10).sort((a,b)=>a-b); if(!mags.length) return 1; const mid=mags[Math.floor(mags.length/2)]; return Math.max(1e-4,mid); }
function compactToScreen(c,s,g){ const r=abs(c); const rho=r===0?0:r/(s+r); const dir=r===0?C(1,0):scale(c,1/r); return {x:g.cx+dir.re*g.inner*rho,y:g.cy-dir.im*g.inner*rho}; }
function compactFromScreen(x,y,s,g){ const dx=(x-g.cx)/g.inner, dy=-(y-g.cy)/g.inner; const rho=Math.min(.985,Math.hypot(dx,dy)); if(rho<1e-12) return C(0,0); const dir=C(dx/rho,dy/rho); return scale(dir,s*rho/(1-rho)); }
function drawCompactValueControl(){ const g=compactWidgetGeometry(), values=criticalValues(), s=compactValueScale(values); const group=svgEl('g'); group.appendChild(svgEl('circle',{cx:g.cx,cy:g.cy,r:g.radius,class:'compact-bg'})); for(const frac of [.5,.75]) group.appendChild(svgEl('circle',{cx:g.cx,cy:g.cy,r:g.inner*frac,class:'compact-ring'})); group.appendChild(svgEl('line',{x1:g.cx-g.inner,y1:g.cy,x2:g.cx+g.inner,y2:g.cy,class:'compact-axis'})); group.appendChild(svgEl('line',{x1:g.cx,y1:g.cy-g.inner,x2:g.cx,y2:g.cy+g.inner,class:'compact-axis'})); const t1=svgEl('text',{x:g.cx,y:g.cy+g.radius-8,'text-anchor':'middle',class:'compact-caption'}); t1.textContent='c'; group.appendChild(t1); const t2=svgEl('text',{x:g.cx,y:g.cy-g.radius+11,'text-anchor':'middle',class:'compact-caption'}); t2.textContent='∞'; group.appendChild(t2); for(const v of values){ const p=compactToScreen(v,s,g); group.appendChild(svgEl('circle',{cx:p.x,cy:p.y,r:3.2,class:'critical-value-node'})); } const cp=compactToScreen(state.c,s,g); const node=svgEl('circle',{cx:cp.x,cy:cp.y,r:7.1,class:'node parameter-node'}); node.addEventListener('pointerdown',e=>startDrag(e,'c',0)); group.appendChild(node); group.addEventListener('pointerdown',e=>{ if(e.target!==group.firstChild) return; startDrag(e,'c',0); const p=evtPoint(e,plot); setC(compactFromScreen(p.x,p.y,s,g)); scheduleRender(true); }); svg.appendChild(group); }
function drawNodeWithCount(p,cls,count,dragKind,index,overlap=false){ const g=svgEl('g'); const isRoot=cls.includes('root-node'), radius=overlap?(isRoot?10.2:5.8):7.2; const node=svgEl('circle',{cx:p.x,cy:p.y,r:radius,class:`node ${cls}${overlap&&isRoot?' root-overlap':''}`}); const bind=el=>el.addEventListener('pointerdown',e=>startDrag(e,dragKind,index)); bind(node); g.appendChild(node); if(count>1){ const sign=overlap&&!isRoot?-1:1, bx=p.x+sign*(radius+1.5), by=p.y-(radius+1.5); const badge=svgEl('circle',{cx:bx,cy:by,r:6.3,class:'count-badge'}); bind(badge); g.appendChild(badge); const tx=svgEl('text',{x:bx,y:by+3,'text-anchor':'middle',class:'count-text'}); tx.textContent=String(count); bind(tx); g.appendChild(tx); } svg.appendChild(g); }
function pathFromPoints(pts){ let d=''; pts.forEach((z,k)=>{const p=toScreen(z);d+=(k?'L':'M')+p.x.toFixed(2)+','+p.y.toFixed(2);}); return d; }
function render(){ const full=state.fullRender; state.fullRender=false; resizeCanvas(); drawBackground(full); clearSvg(svg); drawGrid();
  const hull=convexHull(state.Z); if(hull.length>=2){ let d=''; hull.forEach((z,k)=>{const p=toScreen(z); d+=(k?'L':'M')+p.x.toFixed(2)+','+p.y.toFixed(2);}); if(hull.length>=3)d+='Z'; svg.appendChild(svgEl('path',{d,class:'hull'})); }
  const disk=smallestEnclosingCircle(state.Z), dc=toScreen(disk.center), {w,h}=dims(plot), screenScale=Math.min(w,h)/(2*state.zView.half); svg.appendChild(svgEl('circle',{cx:dc.x,cy:dc.y,r:disk.radius*screenScale,class:'enclosing-disk'})); svg.appendChild(svgEl('line',{x1:dc.x-5,y1:dc.y,x2:dc.x+5,y2:dc.y,class:'disk-center'})); svg.appendChild(svgEl('line',{x1:dc.x,y1:dc.y-5,x2:dc.x,y2:dc.y+5,class:'disk-center'}));
  const wGroups=allClusters(state.W); for(const g of wGroups){ const center=state.W[g[0]]; for(const pts of flowBranches(center,g.length,false)) if(pts.length>1) svg.appendChild(svgEl('path',{d:pathFromPoints(pts),class:'down'})); for(const pts of flowBranches(center,g.length,true)) if(pts.length>1) svg.appendChild(svgEl('path',{d:pathFromPoints(pts),class:'up'})); }
  const zGroups=allClusters(state.Z); const overlaps=(a,groups,pts)=>groups.some(g=>dist(a,pts[g[0]])<=clusterTolerance()*4); zGroups.forEach(g=>{const z=state.Z[g[0]];drawNodeWithCount(toScreen(z),'root-node',g.length,'z',g[0],overlaps(z,wGroups,state.W));});
  wGroups.forEach(g=>{const q=state.W[g[0]];drawNodeWithCount(toScreen(q),'critical-node',g.length,'w',g[0],overlaps(q,zGroups,state.Z));});
  if(state.dragging?.snapTarget){ const p=toScreen(state.dragging.snapTarget); svg.appendChild(svgEl('circle',{cx:p.x,cy:p.y,r:12,class:'snap-preview'})); }
  drawCompactValueControl();
}
function scheduleRender(full=false){ state.fullRender=state.fullRender||full; if(state.renderQueued) return; state.renderQueued=true; requestAnimationFrame(()=>{ state.renderQueued=false; render(); }); }

function startDrag(e,kind,index){ e.preventDefault(); e.stopPropagation(); const p=evtPoint(e,plot); const drag={kind,index,pointerId:e.pointerId,startX:p.x,startY:p.y,moved:false,snapTarget:null}; if(kind==='z') drag.members=exactCluster(state.Z,index); if(kind==='w') drag.members=exactCluster(state.W,index); if(kind==='c'){drag.valueScale=compactValueScale();drag.widget=compactWidgetGeometry();} state.dragging=drag; e.target.setPointerCapture?.(e.pointerId); }
window.addEventListener('pointermove',e=>{ const d=state.dragging; if(!d||e.pointerId!==d.pointerId) return; const p=evtPoint(e,plot); if(Math.hypot(p.x-d.startX,p.y-d.startY)>3) d.moved=true; if(d.kind==='z'||d.kind==='w'){ const pts=d.kind==='z'?state.Z:state.W; const raw=fromScreen(p.x,p.y), targetGroup=nearestSnapCluster(pts,d.members,raw); const target=targetGroup?cloneC(pts[targetGroup[0]]):raw; d.snapTarget=targetGroup?cloneC(target):null; d.members.forEach(i=>pts[i]=cloneC(target)); if(d.kind==='z') setFromRoots(state.Z); else setFromW(true); } else if(d.kind==='c'){ setC(compactFromScreen(p.x,p.y,d.valueScale,d.widget)); } scheduleRender(false); });
window.addEventListener('pointerup',e=>{ const d=state.dragging; if(!d||e.pointerId!==d.pointerId) return; if(!d.moved){ if(d.kind==='z') unsnapCluster('z',d.index); else if(d.kind==='w') unsnapCluster('w',d.index); } state.dragging=null; scheduleRender(true); });
window.addEventListener('pointercancel',()=>{state.dragging=null;scheduleRender(true);});
plot.addEventListener('wheel',e=>{e.preventDefault();const p=evtPoint(e,plot),before=fromScreen(p.x,p.y);const factor=Math.exp(Math.sign(e.deltaY)*.14);state.zView.half=Math.max(.15,Math.min(100,state.zView.half*factor));const after=fromScreen(p.x,p.y);state.zView.cx+=before.re-after.re;state.zView.cy+=before.im-after.im;scheduleRender(true);},{passive:false});
plot.addEventListener('dblclick',e=>{ if(e.target===plot||e.target===svg||e.target===bgCanvas) fitView(); });

document.getElementById('degreeSelect').addEventListener('change',e=>reset(+e.target.value));
document.getElementById('resetBtn').addEventListener('click',()=>reset(state.n));
document.getElementById('fitBtn').addEventListener('click',fitView);
document.getElementById('bgToggle').addEventListener('change',()=>scheduleRender(true));
new ResizeObserver(()=>scheduleRender(true)).observe(document.body);
window.__polyDemo={snapshot:()=>({Z:state.Z.map(cloneC),W:state.W.map(cloneC),c:cloneC(state.c)}),toScreen:z=>toScreen(z),fromScreen:(x,y)=>fromScreen(x,y),fit:fitView};
reset(5);
